language: php

php:
  - "7.4"
  - "8.0"
  - "8.1"

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-scripts --no-interaction
  - composer dump-autoload -o

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
